---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: build latest ml_all image
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    registry: quay.io
    repo: quay.io/logivations/l4t-ros-tf
    privileged: true
    tags:
      - test_latest
      - DRONE_COMMIT_SHA
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch: main

trigger:
  event:
    include:
    - push
