---
# 2/3 PR validation
kind: pipeline
type: docker
name: TEST JOB

platform:
  arch: amd64
  os: linux

clone:
  disable: true

node:
  build: test

steps:
- name: test step1
  image: plugins/git
  commands:
  - sleep 800

