---
# 1.  PR validation
kind: pipeline
type: docker
name: PR validation build docker image

platform:
  arch: amd64
  os: linux

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

image_pull_secrets:
- dockerconfig_prd

steps:
- name: Rebuild nav2 and run tests
  image: ubuntu:latest
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands: 
  - ls


trigger:
  event:
    include:
    - push

