---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    registry: quay.io
    repo: quay.io/logivations/l4t-ros-tf
    auto_tag: "true"
    auto_tag_suffix: linux-amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch: master
    event: push

